name: Elixir CI

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest

   services:
     postgres:
       image: postgres:17
       env:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: pager_test
       ports: ['5432:5432']
       options: >-
         --health-cmd pg_isready
         --health-interval 10s
         --health-timeout 5s
         --health-retries 5
   env:
     MIX_ENV: test
   steps:
   - uses: actions/checkout@v4
   - uses: erlef/setup-beam@v1.18.1
     with:
       elixir-version: '1.18.x'
       otp-version: '27.2.x'
   - uses: actions/cache@v4
     with:
       path: deps
       key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
       restore-keys: |
         ${{ runner.os }}-mix-
   - run: mix deps.get
   - run: mix ecto.create
   - run: mix ecto.migrate
   - run: mix test
